compressionLevel: mixed

enableTelemetry: false

nodeLinker: pnp

# Use local cache instead of global cache
enableGlobalCache: false

packageExtensions:
  better-sqlite3@*:
    dependencies:
      '@types/better-sqlite3': '*'
